### PR TITLE
[TASK] Use docker-compose exec for dockerExec()

### PR DESCRIPTION
**Pull request by tbal**

### CODE REVIEW

**Comment by stucki** [comment]
Can you rebase this change? There's now a 2nd call for `docker exec` in `bin/.config.sh`.

**Comment by tbal** [comment]
Rebased on current develop HEAD.

**Comment by stucki** [comment]
Thanks! :+1:

**Comment by stucki** [comment]
Hmm I just realised that `make mysql-restore` is terribly slow when it uses `docker-compose`. It also prints the whole database dump to `stdout`, which can be suppresed with `docker-compose -T`. However, took longer than 10 minues when I tested just now, compared to `docker exec` (before this PR) which just takes a few seconds to complete.

I assume there's something wrong with `docker-compose exec` and piping data into containers. Therefore, I suggest to abandon this PR or wait until these issues have been sorted out.

How to reproduce:

1. Make a database backup with `make mysql-backup`
2. `make mysql-restore`
3. Apply this PR and repeat

**Comment by mblaschke** [comment]
Isn't docker-compose exec spawning a new container?

**Comment by stucki** [comment]
Nope, it (should) behave similar to `docker exec`, contrary to `docker-compose run` which behaves similar to `docker run` and starts new containers.

**Comment by tbal** [comment]
Thanks for your feedback @stucki. Will check this the next days.

**Comment by tbal** [comment]
I rebased the patch to current develop HEAD and tested it again.

> It also prints the whole database dump to stdout.

I'm just getting this output when running `make mysql-restore` with and without the patch:
```
$ make mysql-restore
 * Starting MySQL restore...
 * Finished
```

> Hmm I just realised that make mysql-restore is terribly slow when it uses docker-compose

I couldn't reproduce this problem either. Same time with or without patch. I tested with a 30MB compressed db dump, which needed ~44 seconds to import.

What versions of docker/docker-compose on which OS are you using?
Mine:
```
Docker version 1.13.1, build 092cba3
docker-compose version 1.11.1, build 7c5d5e4
Ubuntu 14.04, Linux 3.13.0-107-generic #154-Ubuntu SMP
```

**Comment by htuscher** [comment]
I can tell you using docker-compose exec sometimes leads to unexpected behavior as docker-compose is written in python and is parsing the run arguments. In some rare cases you end up with escaping issues so using docker exec as currently is a better solution.

**Comment by stucki** [comment]
Tested here again: When I apply this patch, `make mysql-backup` currently fails here on Ubuntu 16.04 using latest Docker (17.06) and docker-compose (1.15). Without the patch it's working fine. So yes it could well be like @hhoechtl mentions that there are some quoting issues when using docker-compose...

**Comment by tbal** [comment]
Since I created this PR I also got some edge cases where docker-compose exec broke things, especially during CI stuff.
I'm ok with abandoning this PR.

**Pull request closed without merging**
