### PR TITLE
Set MYSQL_HOST and MYSQL_PORT in environment.yml

### PR DESCRIPTION
**Pull request by stucki**
This was missing even though it was already documented in DOCKER-INFO.md.

### CODE REVIEW

**Comment by mblaschke** [comment]
Do we need these env vars? Maybe users are thinking about changing them and do not realise that they are not changing anything.

**Comment by stucki** [comment]
Yes I need them, that's why I made the PR :-)

**Comment by mblaschke** [comment]
Should we add a comment above these variables? just a hint that these variables are just for the application and doesn't change anything?

**Comment by stucki** [comment]
I don't see what you mean. The same applies for all MYSQL_* env variables. What's special about MYSQL_HOST and MYSQL_PORT?

**Comment by mblaschke** [comment]
See https://hub.docker.com/_/mysql/
These variables controls the mysql container.

**Comment by tbal** [comment]
> What's special about MYSQL_HOST and MYSQL_PORT?

As far as i understand @mblaschke, the problem with the MYSQL_HOST env variable is, that changing it wouldn't affect anything, the mysql container is still only reachable by using the host name `mysql`, as far as you do not change its container service name in the `docker-compose.yml` accordingly.
Users could oversee this easily and think of a faulty behaviour.

Apart from that, when changing the container service name of e.g. the mysql container, some of the helper scripts would break currently, while they use the hardcored service name `mysql`.

In case of MYSQL_PORT I don't see a use case why this would/should change. What's your use case?

A reason of defining this variables would be to use env vars in the TYPO3 config all the way and not having a mix of variables (db, password, user) and hardcoded settings (host, port).
But nevertheless I wouldn't recommend defining this two variables in the environment.yml without further handling of the mentioned concerns.

**Comment by stucki** [comment]
Thanks, I see. Was not even aware of this, but it looks like an interesting feature, so we should not touch it! :-)

The reason why I came up with this suggestion is because I'm thinking about using Helmuts [dotenv-connector](https://github.com/helhum/dotenv-connector) in my projects.

So how about this: We add new variables which are not parsed anywhere (so they are in fact read-only). Suggestion:
```
DATABASE_USER=$MYSQL_USER
DATABASE_PASSWORD=$MYSQL_PASSWORD
DATABASE_NAME=$MYSQL_DATABASE
DATABASE_HOST="mysql"
DATABASE_PORT=3306
```

**Review by htuscher — APPROVED** [review]
We do the same in our projects. So that's fine for me if it is in the general boilerplate

**Comment by stucki** [comment]
@hhoechtl Nope please don't merge this! Like I wrote above, it should be solved using additional environment variables. My suggestion for this is `DB_*` but let me know what you prefer...

**Comment by stucki** [comment]
(Reopening after I accidentially deleted the feature branch.)

**Review by htuscher — APPROVED** [review]

**Pull request merged**
