### PR TITLE
[FEATURE] run composer inside a container

### PR DESCRIPTION
**Pull request by htuscher**
This solves the issue that you might not have a compatible PHP
version of PHP on your local computer to meet the architecture
requirements.

### CODE REVIEW

**Comment by htuscher** [comment]
@mblaschke or @PanadeEdu or @jousch could you review and merge this?

**Comment by josefglatz** [comment]
@hhoechtl While developing it's annoying to always switch into app's shell to run TYPO3 cli tasks which do some database operations. Is there any solution to add such a support for recurring tasks?

**Comment by htuscher** [comment]
@jousch What do you mean exactly? We have:
`make scheduler extbase:help` which executes the `typo3/cli_dispatch.sh scheduler extbase:help` inside the app container so you don't have to go into the app container.

**Comment by josefglatz** [comment]
@hhoechtl ah thx for the hint. Background: I'm using ext:typo3_console from helhum and don't commit my PackageStates.php. So I have an alternative cli entrypoint next to `/typo3` symlink called `/typo3cms`. After composer finished autoload-dump, my custom scripts are started.

**Pull request merged**
